project_id = "euro-2028-predictor-local"

[db]
major_version = 17

[auth]
site_url = "http://127.0.0.1:4174"
additional_redirect_urls = ["http://127.0.0.1:4173/**", "http://127.0.0.1:4174/**"]

[auth.email]
enable_confirmations = true
