/**
 * THE ACTION CENTRE — everything the server says needs the player, or has
 * happened to them, across every competition they play.
 *
 * ============================ WHY THIS EXISTS AT ALL =====================
 *
 * `player_action_items` is generated by five server drivers and has had a
 * `pg_cron` caller since contract 172. Until the Football Hub cutover its only
 * consumer was the legacy `AppShell` AppBar; the cutover made `vNextOwnsFrame`
 * true for every Hub destination, and that branch renders no AppBar — so the
 * feed became unreachable from the production frame. This is the vNext side of
 * it, and it adds no capability: every read and write it uses was already
 * installed and already granted.
 *
 * ============================ IT IS NOT THE ATTENTION LAYER ==============
 *
 * `ShellAttentionItem` answers *"what needs doing in a competition you are not
 * currently looking at"* and is derived live from each competition's own week.
 * This answers *"what has the server recorded for you, and have you seen it"* —
 * which is a different question, includes news as well as work, and is the only
 * one of the two with durable cross-device state.
 *
 * The two therefore coexist deliberately rather than by omission. Nothing here
 * decides urgency, and nothing here filters by the current competition.
 *
 * ============================ AND IT DECIDES NOTHING =====================
 *
 * PURE PRESENTATION over a server payload. It does not decide that an action
 * exists, when it expires, whether it is complete, or what order it is in —
 * `get_my_actions` orders by `priority`, then `deadline_at`, then `action_key`,
 * and that order is consumed rather than reproduced. No clock is read.
 */

/**
 * THE FIVE THINGS THE SERVER GENERATES, AS A CLOSED SET.
 *
 * Written as a union so a sixth generator added to the database fails to
 * compile here rather than silently rendering as a blank row. `unknown` is the
 * deliberate escape hatch for exactly that case — see `actionKindOf`.
 */
export type VNextActionKind =
  | 'matchweek-predictions-due'
  | 'lms-pick-due'
  | 'cup-penalty-number-due'
  | 'matchweek-settled'
  | 'game-consequence'
  | 'unknown'

/**
 * WHETHER THIS IS WORK OR NEWS.
 *
 * The distinction is the server's `action_type` and not a judgement made here.
 * It matters because the two belong under different headings: a player scanning
 * for what they owe must not have to read past three settled matchweeks to find
 * a pick that locks in an hour.
 */
export type VNextActionClass = 'needs-you' | 'news'

const NEEDS_YOU: ReadonlySet<VNextActionKind> = new Set<VNextActionKind>([
  'matchweek-predictions-due',
  'lms-pick-due',
  'cup-penalty-number-due',
])

/**
 * THE THREE GAMES THIS PLATFORM HAS A vNEXT SURFACE FOR.
 *
 * The database's `game_key` vocabulary is wider — `ko_predictor`,
 * `main_predictor` and `original_predictor` also exist — so this is
 * deliberately NOT that enum. It is the subset a player can be taken to, and a
 * `game_key` outside it resolves to `null` rather than to a plausible
 * neighbour: sending somebody to Last Man Standing because their knockout
 * predictor had no route is worse than not offering the link.
 */
export type VNextActionGame = 'match-predictor' | 'last-man-standing' | 'championship'

export type VNextActionItem = {
  /** The server's `action_key`. The identity, and the argument to every write. */
  readonly key: string
  readonly kind: VNextActionKind
  readonly actionClass: VNextActionClass
  /**
   * WHICH GAME THIS IS ABOUT, or `null` where the payload does not say and the
   * kind does not imply one.
   *
   * It is the model's answer to *what*; **the route is not decided here.** A
   * host turns this plus `contextId` into an address, because which URL a game
   * lives at is a routing fact and this lane must not hold one — the same split
   * `useGlobalPlayInbox` used when it resolved destinations outside its model.
   */
  readonly game: VNextActionGame | null
  /**
   * THE COMPETITION THIS BELONGS TO, as the tournament id and never a name.
   * Two seasons of one competition legitimately share a display name, so a
   * surface joining on one would send a player to the wrong season.
   */
  readonly contextId: string
  /** The bonus competition, where the action has one. Never a label. */
  readonly competitionId: string | null
  /**
   * The competition's name, WHERE THE SHELL KNEW IT. `null` where the player's
   * competition list holds no context for `contextId` — which is a real state
   * and not an error, and which the surface says rather than papers over.
   */
  readonly competitionName: string | null
  /** What the item says, composed only from fields the payload carried. */
  readonly headline: string
  /**
   * The supporting sentence, or `null` where the context carried nothing to
   * make one from. `null` renders as nothing; it is never replaced by a
   * plausible default.
   */
  readonly detail: string | null
  /** The server's instant, unformatted. Presentation formats it; nothing here does. */
  readonly deadlineAt: string | null
  /** Whether the server has recorded that this player has seen it. */
  readonly seen: boolean
}

export type VNextActionsModel = {
  /** The server's own unseen count. NEVER derived by counting `seen === false`. */
  readonly unseen: number
  /** In the server's order, which is priority then deadline then key. */
  readonly items: readonly VNextActionItem[]
}

/**
 * WHAT THE SERVER'S `action_type` MEANS HERE.
 *
 * An unrecognised type resolves to `unknown` rather than throwing. The service
 * layer's own comment records why: the presentation layer has a safe generic
 * label, and a database that has begun generating a sixth kind must not empty
 * a player's inbox in a build that predates it.
 */
export function actionKindOf(actionType: string): VNextActionKind {
  switch (actionType) {
    case 'matchweek_predictions_due':
      return 'matchweek-predictions-due'
    case 'lms_pick_due':
      return 'lms-pick-due'
    case 'cup_penalty_number_due':
      return 'cup-penalty-number-due'
    case 'matchweek_settled':
      return 'matchweek-settled'
    case 'game_consequence':
      return 'game-consequence'
    default:
      return 'unknown'
  }
}

/**
 * WORK OR NEWS.
 *
 * `unknown` is NEWS, deliberately. A kind this build cannot interpret must not
 * be filed under "needs you": telling a player they owe something and being
 * unable to say what is worse than reporting it quietly, and an unrecognised
 * item carries no deadline this build can trust.
 */
export function actionClassOf(kind: VNextActionKind): VNextActionClass {
  return NEEDS_YOU.has(kind) ? 'needs-you' : 'news'
}

/**
 * WHETHER THIS ROW CAN BE TAKEN ANYWHERE AT ALL.
 *
 * ============================ WHY THE MODEL DECIDES THIS =================
 *
 * Not the route — the route is a host's answer and this lane holds none. What
 * this decides is whether a destination EXISTS to resolve, which the surface
 * needs before it chooses between a button and a paragraph. A row rendered as a
 * control that does nothing when pressed is the affordance teaching a player
 * the product is broken, and `ActionCentreBody` would otherwise draw one for
 * every item the moment a host supplied any `onOpenItem`.
 *
 * ============================ THE TWO CONDITIONS =========================
 *
 * **It must name a competition the player's own list covers.** `competitionName`
 * is `null` exactly when the membership read did not return that tournament id,
 * and that list is the only thing that turns an identity into an address — so a
 * null name and an unresolvable route are the same fact reaching two places.
 *
 * **And it must be addressable within that competition.** A settled matchweek
 * always is, because the competition's own Home carries the recap. Everything
 * else needs a `game` this build has a surface for; `null` there is a
 * `game_key` with no vNext route, or a kind this build cannot interpret.
 */
export function actionIsOpenable(item: VNextActionItem): boolean {
  if (item.competitionName === null) return false
  return item.kind === 'matchweek-settled' || item.game !== null
}

/** The items that need the player, in the server's order. */
export function actionsNeedingYou(
  model: VNextActionsModel,
): readonly VNextActionItem[] {
  return model.items.filter((item) => item.actionClass === 'needs-you')
}

/** The items that are news, in the server's order. */
export function actionsNews(model: VNextActionsModel): readonly VNextActionItem[] {
  return model.items.filter((item) => item.actionClass === 'news')
}

/**
 * THE KEYS WHOSE SEEN STATE HAS NOT YET BEEN RECORDED.
 *
 * The argument to `mark_actions_seen`, computed from what the server said
 * rather than from anything the browser remembers — which is what makes the
 * state cross-device rather than per-tab.
 */
export function unseenActionKeys(model: VNextActionsModel): readonly string[] {
  return model.items.filter((item) => !item.seen).map((item) => item.key)
}
