import { describe, expect, it } from 'vitest'
import { isLeagueSeasonCompetitionConfig } from '../../src/domain/competition/kinds'
import {
  MATCHWEEK_COUNT,
  SEASON_CLUBS,
  SEASON_CONFIG,
  SEASON_FIXTURES,
  fixturesForMatchweek,
  instantFor,
  matchweekScopeId,
  resolveSeasonPreview,
} from '../../src/dev/seasonPreviewFixture'

/**
 * The season half of the competition seam, driven end to end.
 *
 * `LeagueSeasonCompetitionConfig` has existed since the Stage B context
 * foundation, and until this fixture nothing outside a unit test ever handed one
 * to `resolveCompetitionContext`. The seam was therefore *typed* for a season
 * and never *exercised* as one — a distinction that only shows up when someone
 * tries to build the surface and finds out which half works.
 *
 * So these assertions are about the engine, not the preview page. If the season
 * lock policy, the league phase or the match-state ladder stops behaving, this
 * fails whether or not anyone has opened `/dev/season`.
 *
 * The schedule assertions are here for a duller reason: the fixture list is
 * generated by the circle method rather than written out, and a rotation bug
 * produces a schedule that looks plausible and is wrong — a club playing twice
 * in a matchweek, or never away.
 */

const MATCHWEEK = 5
const SCOPE = matchweekScopeId(MATCHWEEK)

/** The engine at `offsetMinutes` relative to the matchweek's earliest kickoff. */
function contextAt(offsetMinutes: number, options: Record<string, unknown> = {}) {
  return resolveSeasonPreview(instantFor(MATCHWEEK, offsetMinutes), {
    matchweek: MATCHWEEK,
    ...options,
  })
}

describe('the synthetic season is a valid competition', () => {
  it('satisfies the domain guard for a league season', () => {
    // Not a cast. If the config drifts out of shape — a lock scope count that
    // no longer matches the matchweek count, say — the engine would silently
    // treat the lock configuration as invalid and every scope would fail
    // closed, which reads as "the lock works" while proving nothing.
    expect(isLeagueSeasonCompetitionConfig(SEASON_CONFIG)).toBe(true)
    expect(SEASON_CONFIG.lockPolicy.scope).toBe('matchweek')
    expect(SEASON_CONFIG.lockPolicy.bufferMinutes).toBe(30)
    expect(SEASON_CONFIG.lockPolicy.scopeCount).toBe(MATCHWEEK_COUNT)
  })

  it('keeps the competition time zone off the viewer', () => {
    // The seam's whole reason for existing: which matchweek a fixture belongs
    // to cannot have two answers.
    expect(SEASON_CONFIG.competitionTimeZone).toBe('Europe/London')
  })
})

describe('the generated schedule is a real double round-robin', () => {
  it('plays every matchweek in full', () => {
    expect(SEASON_FIXTURES).toHaveLength((SEASON_CLUBS.length / 2) * MATCHWEEK_COUNT)

    for (let matchweek = 1; matchweek <= MATCHWEEK_COUNT; matchweek += 1) {
      expect(fixturesForMatchweek(matchweek)).toHaveLength(SEASON_CLUBS.length / 2)
    }
  })

  it('gives every club exactly one fixture per matchweek', () => {
    // The rotation bug that matters: a club paired with itself, or appearing
    // twice in a week, still yields ten fixtures and the right total.
    for (let matchweek = 1; matchweek <= MATCHWEEK_COUNT; matchweek += 1) {
      const appearances = fixturesForMatchweek(matchweek).flatMap((fixture) => [
        fixture.home.id,
        fixture.away.id,
      ])
      expect(new Set(appearances).size, `matchweek ${matchweek}`).toBe(SEASON_CLUBS.length)
    }
  })

  it('plays every club home and away exactly once', () => {
    const played = new Map<string, { home: number; away: number }>()
    for (const club of SEASON_CLUBS) played.set(club.id, { home: 0, away: 0 })

    const orderedPairs = new Set<string>()
    for (const fixture of SEASON_FIXTURES) {
      played.get(fixture.home.id)!.home += 1
      played.get(fixture.away.id)!.away += 1
      orderedPairs.add(`${fixture.home.id}v${fixture.away.id}`)
    }

    // Every ordered pair once — no repeated fixture, and no pair missed.
    expect(orderedPairs.size).toBe(SEASON_CLUBS.length * (SEASON_CLUBS.length - 1))

    for (const [clubId, counts] of played) {
      expect(counts, clubId).toEqual({
        home: SEASON_CLUBS.length - 1,
        away: SEASON_CLUBS.length - 1,
      })
    }
  })
})

describe('kickoffs are wall-clock in the competition zone, across the clock change', () => {
  /** The competition's own reading of a kickoff — never the viewer's zone. */
  const inCompetitionZone = (iso: string) =>
    new Intl.DateTimeFormat('en-GB', {
      timeZone: SEASON_CONFIG.competitionTimeZone,
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    }).format(new Date(iso))

  // Matchweek 1 falls in August (BST, UTC+1); the clocks go back on Sunday
  // 31 October 2027, so matchweek 13 falls in November (GMT, UTC+0).
  const august = fixturesForMatchweek(1)[1]
  const november = fixturesForMatchweek(13)[1]

  it('is a Saturday 15:00 kickoff in both, to anyone reading the competition', () => {
    expect(inCompetitionZone(august.kickoffAt)).toBe('15:00')
    expect(inCompetitionZone(november.kickoffAt)).toBe('15:00')
  })

  it('is nevertheless a different UTC instant either side of the change', () => {
    // The whole point. A fixed offset would make both 14:00Z or both 15:00Z,
    // and every fixture after October would be an hour wrong — the failure the
    // competitionTimeZone seam exists to prevent. The lock derives from these
    // instants, so getting it wrong moves a matchweek deadline by an hour.
    expect(new Date(august.kickoffAt).getUTCHours()).toBe(14)
    expect(new Date(november.kickoffAt).getUTCHours()).toBe(15)
  })
})

describe('the matchweek lock behaves as a season, not a tournament', () => {
  it('is open an hour before the first kickoff', () => {
    const lock = contextAt(-60).lockScopes[SCOPE]
    expect(lock.locked).toBe(false)
    expect(lock.reason).toBe('before_scope_lock')
  })

  it('locks 30 minutes before the first kickoff, not at kickoff', () => {
    // This is the difference from the tournament in one assertion. A tournament
    // entry locks once at a single deadline with a zero buffer; a season locks
    // per matchweek, half an hour early, and does it again next week. Nothing in
    // the UI branches on this — it falls out of `lockPolicy`.
    const lock = contextAt(-29).lockScopes[SCOPE]
    expect(lock.locked).toBe(true)
    expect(lock.reason).toBe('scope_lock_reached')
  })

  it('locks each matchweek independently', () => {
    // The rolling part. With matchweek 5 locked, matchweek 6 must still be open
    // — a season that locked everything at once would be a tournament.
    const context = contextAt(-29)
    expect(context.lockScopes[SCOPE].locked).toBe(true)
    expect(context.lockScopes[matchweekScopeId(MATCHWEEK + 1)].locked).toBe(false)
  })

  it('fails closed when fixture data is missing or stale', () => {
    // A lock derived from kickoff times has to answer for not having them.
    expect(contextAt(-60, { missingFixtureData: true }).lockScopes[SCOPE]).toMatchObject({
      locked: true,
      reason: 'missing_fixture_data',
    })
    expect(contextAt(-60, { staleFixtureData: true }).lockScopes[SCOPE]).toMatchObject({
      locked: true,
      reason: 'stale_fixture_data',
    })
  })
})

describe('the league phase and match states resolve', () => {
  it('reports a league stage in progress rather than a group or knockout one', () => {
    expect(contextAt(-60).competitionPhase).toEqual({
      state: 'stage_in_progress',
      stageKind: 'league',
    })
  })

  it('reports the competition kind it was configured with', () => {
    expect(contextAt(-60).competitionKind).toBe('league_season')
  })

  it('moves a fixture from editable to locked to in-play', () => {
    const earliest = fixturesForMatchweek(MATCHWEEK)[0]
    const stateAt = (offset: number, options: Record<string, unknown> = {}) =>
      contextAt(offset, options).matches.find((match) => match.id === earliest.id)?.state

    expect(stateAt(-60)).toBe('scheduled_editable')
    expect(stateAt(-29)).toBe('scheduled_locked')
    expect(stateAt(60)).toBe('in_play_feed')
  })

  it('distinguishes a match with no feed from one that is not being played', () => {
    // `in_play_no_feed` exists because "we cannot see it" and "it is not
    // happening" are different answers, and the preview must be able to show
    // the difference.
    const earliest = fixturesForMatchweek(MATCHWEEK)[0]
    const context = contextAt(60, { feedAvailable: false })
    const match = context.matches.find((candidate) => candidate.id === earliest.id)

    expect(match?.state).toBe('in_play_no_feed')
    expect(match?.overlays).toContain('feed_unavailable')
  })
})
