import type { SiteVariant } from './siteVariant.js'

/**
 * The icon set and the two theme colours each deployment publishes.
 *
 * ONE HOME FOR A FACT THAT HAD THREE. The dark and light chrome colours were
 * written out separately in `documentMetadata.ts` (the `theme-color` metas) and
 * in `app/providers/ThemeProvider.tsx` (which rewrites those metas when the
 * player picks a theme), each carrying a comment telling the reader to keep it
 * in step with `--bg` in `src/styles/tokens.css`. They had drifted: both said
 * `#0A1128`, and `--bg` has resolved through `--surface-page` to `--n-1`
 * since the neutral ramp landed. A web app manifest needs the same two values a
 * third time — as `theme_color` and `background_color`, which paint the
 * installed application's window and its launch screen — so the copy is
 * collapsed here rather than tripled, and `tests/app/themeColourParity.test.ts`
 * reads `tokens.css` and refuses a future drift.
 *
 * WHY THE ICONS ARE PER VARIANT. `public/` is copied verbatim into both
 * deployments, so one icon set there is one installed identity for two
 * products. A `<title>` is corrected by a reload; a home-screen icon outlives
 * the tab. The bytes live in `assets/site-icons/<variant>/`, generated by
 * `scripts/og/generate-site-icons.mjs`, and `vite.config.ts` emits only the
 * variant being built.
 *
 * Pure and Node-importable, for the same reason `sitePublicMetadata.ts` is: the
 * build reads it, and so does the generator that draws the files.
 */

/** `--acc` in `src/styles/tokens.css`: the colour the mark is drawn in. */
export const ICON_ACCENT = '#22E06C'

/** Hex values of `--n-1`, which `--bg` resolves to, in each theme. */
export const THEME_COLOUR = {
  dark: '#080D1F',
  light: '#F6F4EF',
} as const

export type SiteIcon = {
  /** File name inside `assets/site-icons/<variant>/` and under the site root. */
  readonly file: string
  readonly size: number
  readonly purpose: 'any' | 'maskable'
}

/**
 * The raster icons every deployment publishes.
 *
 * 192 and 512 are the two sizes the installability criteria actually check;
 * the maskable 512 is what stops Android drawing the tile inside a white
 * circle, and Apple's touch icon is the iOS home screen, which reads no
 * manifest at all.
 */
export const SITE_ICON_SIZES: readonly SiteIcon[] = [
  { file: 'apple-touch-icon.png', size: 180, purpose: 'any' },
  { file: 'icon-192.png', size: 192, purpose: 'any' },
  { file: 'icon-512.png', size: 512, purpose: 'any' },
  { file: 'icon-maskable-512.png', size: 512, purpose: 'maskable' },
]

/** Every file emitted for one site, raster set plus the ICO fallback. */
export const SITE_ICON_FILES: readonly string[] = [
  ...SITE_ICON_SIZES.map((icon) => icon.file),
  'favicon.ico',
]

/** Where one variant's committed icon bytes live, relative to the repository. */
export function siteIconDirectory(variant: SiteVariant): string {
  return `assets/site-icons/${variant}`
}

/**
 * What is drawn on one site's tile.
 *
 * NOT `brand.monogram`, AND THAT IS THE POINT. The monogram is the collapsed
 * rail's two or three characters, chosen to fit a 32-pixel button beside a
 * product name that is already on screen. An application icon is read with no
 * such context — on a home screen, in a task switcher, in a share sheet — and
 * "PH" standing alone there reads as something the product is not. The Hub gets
 * a drawn mark instead, and the tournament keeps the numerals that ARE its
 * name.
 */
export type SiteIconMark =
  /**
   * The centre mark of a football pitch — halfway line, centre circle, centre
   * spot. It is the most widely read football glyph there is, it is pure
   * geometry so it depends on no installed typeface and survives a 16-pixel
   * favicon, and it is the one image that says "a match is about to start",
   * which is what a weekly prediction deadline actually is.
   */
  | { readonly kind: 'pitch' }
  /** Numerals drawn in the product's own typeface. */
  | { readonly kind: 'wordmark'; readonly text: string }

export function siteIconMark(variant: SiteVariant): SiteIconMark {
  return variant === 'euro'
    ? { kind: 'wordmark', text: '28' }
    : { kind: 'pitch' }
}

/**
 * The pitch mark in one unit square, so the canvas generator and the SVG
 * favicon draw the SAME geometry rather than two drawings that merely look
 * alike today. Every value is a fraction of the tile.
 */
export const PITCH_MARK = {
  /**
   * The halfway line runs the full width of the tile, touchline to touchline,
   * because that is what a halfway line does — and because a line that stops
   * short of the edge turns the mark into a Greek letter rather than a pitch.
   * The tile itself is the pitch, so on a maskable icon the platform's crop is
   * what shortens the line, and only the circle and spot are pulled inside the
   * safe zone.
   */
  lineFrom: 0,
  lineTo: 1,
  lineWidth: 0.07,
  circleRadius: 0.26,
  circleWidth: 0.085,
  spotRadius: 0.075,
} as const

/**
 * How far the mark is pulled in on a maskable tile.
 *
 * A maskable icon must survive an arbitrary platform mask, and the guarantee
 * the specification gives is a SAFE CIRCLE of 80% of the tile's width — so
 * anything meaningful has to sit within a radius of 0.4 of the centre. This
 * scale is what puts the centre circle there; `installablePwa.test.ts`
 * multiplies the two and refuses a mark that would be cropped on a device
 * nobody here owns.
 */
export const MASKABLE_SAFE_SCALE = 0.74

/**
 * This site's `favicon.svg`, generated rather than committed.
 *
 * A tile and a mark is all it is, so it is text — and text generated from the
 * site authority cannot fall out of step with the product it belongs to the way
 * a second committed file can. The pitch mark is drawn from `PITCH_MARK`, the
 * same geometry the raster generator uses, so the two cannot diverge.
 *
 * A wordmark falls back to a geometric sans where Space Grotesk is not
 * installed, because a favicon rendering context loads no webfont. At 16 pixels
 * the two are indistinguishable, which is the trade the hand-authored file made
 * before this; the pitch mark has no such dependency at all.
 */
export function faviconSvg(mark: SiteIconMark, label: string): string {
  const body =
    mark.kind === 'pitch'
      ? pitchSvg(64)
      : `<text x="32" y="34" fill="${ICON_ACCENT}" text-anchor="middle" dominant-baseline="central"
        font-family="'Space Grotesk', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif"
        font-weight="500" font-size="36" letter-spacing="0.5">${escapeXml(mark.text)}</text>`

  return `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64" role="img" aria-label="${escapeXml(label)}">
  <rect width="64" height="64" rx="14" fill="${THEME_COLOUR.dark}"/>
  ${body}
</svg>
`
}

/** The pitch mark as SVG, from the shared geometry above. */
function pitchSvg(size: number): string {
  const centre = round(size / 2)
  const m = PITCH_MARK
  return `<g stroke="${ICON_ACCENT}" fill="none">
    <line x1="${round(m.lineFrom * size)}" y1="${centre}" x2="${round(m.lineTo * size)}" y2="${centre}" stroke-width="${round(m.lineWidth * size)}" />
    <circle cx="${centre}" cy="${centre}" r="${round(m.circleRadius * size)}" stroke-width="${round(m.circleWidth * size)}" />
    <circle cx="${centre}" cy="${centre}" r="${round(m.spotRadius * size)}" fill="${ICON_ACCENT}" stroke="none" />
  </g>`
}

function round(value: number): number {
  return Math.round(value * 100) / 100
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
